#!/bin/bash
#
# Description:
#
# This script starts unison sync jobs under the following conditions and
# checks:
#
#   1. If the logfile has problems, send an e-mail.
#   2. If did not run for a long time, send an e-mail
#   3. If this job is aready running, do nothing.
#   4. Start only if the network peers distance is <=x hops
#   5. Start!
#
# Install:
#   $ sudo install -o root -g root -m 755 unison-cron /usr/local/bin
#
# Usage:
#   ./unison-cron server sync-to-server.prf email@domain.tld
#
# Cron job configuration:
#   $ crontab -e
#   PATH="/usr/bin/:/bin:/usr/local/bin"
#   EMAIL="email@domain.tld"
#   */5 * * * * unison-cron server sync-to-server.prf email@domain.tld
#
# Changelog:
#   2015-12-02 Marco Balmer - Initial

# Vars
TMPDIR=/var/tmp
HOST=$1
CONFIG=$2
EMAIL=$3
LOCKFILE="`basename $0`-${LOGNAME}-${CONFIG}.lock"
FLAG=${TMPDIR}/${LOCKFILE}

# Functions
check_lockfile()
{

# Remove lockfile after 24 hours.
find ${TMPDIR} -maxdepth 1 -name "${LOCKFILE}" -mtime +1 -delete;

if [ -f "${FLAG}" ];
then
  return 0
else
  return 1
fi
}

check_unison_process()
{
if ps -ef | grep $LOGNAME | grep "unison $CONFIG" | grep -vE "grep|ssh|bash" &>/dev/null;
then
  return 1
else
  return 0
fi
} # check_unison

check_unison_logfile()
{
if ! tail -n 5 ~/unison-${CONFIG}.log | grep "Synchronization complete" >/dev/null;
then
  if ! check_lockfile;
  then
  cat << EOF | mailx -s "$HOSTNAME:~$LOGNAME | $CONFIG | Synchronization is late!" $EMAIL
`tail -n 5 ~/unison-${CONFIG}.log`
EOF
  touch ${FLAG}
  fi
fi

if find ~/  -maxdepth 1 -name "unison-${CONFIG}.log" -mtime +3 | egrep '.*' >/dev/null;
then
  if ! check_lockfile;
  then
 cat << EOF | mailx -s "$HOSTNAME:~$LOGNAME | $CONFIG | Logfile is too old!" $EMAIL
`tail -n 5 ~/unison-${CONFIG}.log`
EOF
  touch ${FLAG}
  fi
fi

return 0
}

check_network()
{
# If there is no answer default gateways dns port, stopp here!
nc -z `ip r | grep default | cut -d ' ' -f 3` 53 &>/dev/null || return 1

if ! unison -testServer $CONFIG &>/dev/null;
then
  return 1
fi

Hops=`tracepath6 $HOST | wc -l`

if [ "$Hops" -gt "11" ];
then
  # Do not start if to many hops to the server. We assume we are not in local
  # wlan.
  return 1
fi

return 0
} # check_network

start_unison()
{

cat << EOF | mailx -s "$HOSTNAME:~$LOGNAME/.unison/$CONFIG started, YEAH!!" $EMAIL
`tail -n 2 ~/unison*.log`
EOF

unison $CONFIG -batch -auto -repeat 300 -silent &

} # start_unison

# Main

if [ -z $HOST ] || [ -z $CONFIG ] || [ -z $EMAIL ];
then
  echo "Usage: ./unison-cron server sync-to-server.prf email@domain.tld"
  exit 3
fi

# Main
check_unison_logfile && check_unison_process && check_network && start_unison
